# Generated by Django 3.2 on 2023-11-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyingmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='hash_id',
        ),
    ]
