# Generated by Django 3.2 on 2023-11-29 20:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flightmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
