# Generated by Django 3.2 on 2023-11-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightmanager', '0002_country_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
    ]
