# Generated by Django 3.2 on 2023-11-29 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flightmanager', '0005_auto_20231130_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='passengers',
            field=models.ManyToManyField(related_name='flights', to=settings.AUTH_USER_MODEL),
        ),
    ]
