# Generated by Django 3.2 on 2023-11-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
        ('flightmanager', '0006_alter_flight_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='passengers',
            field=models.ManyToManyField(related_name='flights', to='usermanagement.normal_user'),
        ),
    ]
