# Generated by Django 3.2 on 2023-11-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightmanager', '0007_alter_flight_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='passengers',
        ),
        migrations.AlterField(
            model_name='airplane',
            name='capacity',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
