# Generated by Django 3.2 on 2023-11-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20231130_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normal_user',
            name='email',
        ),
    ]
